package cfg

const (
	UDP_PORT_INWARD  = 6438
	UDP_PORT_OUTWARD = 6439

	TCP_PORT        = 6440
	FILE_SLICE_SIZE = 4096
	HEAD_SIZE       = 4

	ASK_FOR_AVAILABLE_DEVICES = 1000
	SEARCH_FOR_DEVICE         = 1001
	ACK_BEING_DISCOVERED      = 1002
	ACK_I_AM_THE_DEVICE       = 1003
	READY_TO_SEND_FILE        = 1004
	READY_TO_RECV_FILE        = 1005
	REFUSED_TO_RECV_FILE      = 1006

	CACHED_UDP_READ_CHANNEL_MAX_BUFFER = 5
	MAX_DEVICE_DISCOVER_TIMEOUT        = 3
	MAX_STANDBY_ACK_TIMEOUT            = 5
	MAX_STANDBY_RECEIVE_TIMEOUT        = 300
	MAX_TCP_DIAL_TIMEOUT               = 1
	MAX_TCP_READ_TIMEOUT               = 1
	MAX_TCP_WRITE_TIMEOUT              = 1

	TRANSOWL_FLAG = "0x3d"

	ACK_PACKET_RECV = "-=ok=-"
	ACK_SEND_DONE   = "-=sdone-="
	ACK_RECV_DONE   = "-=rdone=-"
	ACK_ERROR       = "-=error=-"

	NETTYPE_SAMESEGMENT = 3000
	NETTYPE_WHOLENET    = 3001

	STATUS_OK        = 4001
	STATUS_RECV_FILE = 4002
	STATUS_SEND_FILE = 4003
)
