name: Build
on:
  push:
    branches: [master]
    tags: [v*]
permissions:
  contents: write
jobs:
  goreleaser:
    name: Goreleaser
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'v') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          # More assembly might be required: Docker logins, GPG, etc. It all depends
          # on your needs.
      - uses: goreleaser/goreleaser-action@v4
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.TRANSOWL_TOKEN }}